name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [melodic, noetic]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build the Docker image
      run: |
        docker build .                              \
          --build-arg ROS_DISTRO=${{ matrix.node }} \
          --file Dockerfile                         \
          --tag ouster-ros-${{ matrix.node }}:$(date +%s)
